---
- stat: path=/usr/local/share/ca-certificates/cacert-root.crt
  register: root

- stat: path=/usr/local/share/ca-certificates/cacert-class3.crt
  register: class3

- name: Install CACert root certificate
  get_url: url={{http://www.cacert.org/certs/root.crt}} dest={{/usr/local/share/ca-certificates/cacert-root.crt}}
  when: not root.stat.exists
  notify:
    - Update certificates

- name: Install CACert class3 certificate
  get_url: url={{http://www.cacert.org/certs/class3.crt}} dest={{/usr/local/share/ca-certificates/cacert-class3.crt}}
  when: not class3.stat.exists
  notify:
    - Update certificates

- name: Install packages
  apt:
    pkg: nslcd libpam-ldapd libnss-ldapd
    state: latest
